version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Deployment begins"
      - export JAVA_HOME="$JAVA_17_HOME"
      - aws apigateway create-rest-api --name "MyAPI" --region us-east-1
