version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      # Define your OpenAPI specification for the API Gateway
      - |
        cat <<EOF > api_definition.yaml
        openapi: "3.0.0"
        info:
          title: "My API"
          version: "1.0.0"
          description: "Description of my API"
          contact:
            name: "John Doe"
            email: "john.doe@example.com"
        paths:
          /resource1:
            get:
              summary: "Retrieve a greeting"
              responses:
                "200":
                  description: "A successful response"
                  content:
                    application/json:
                      schema:
                        type: "object"
                        properties:
                          message:
                            type: "string"
                            example: "Hello, World!"

            post:
              summary: "Submit a greeting"
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: "object"
                      properties:
                        name:
                          type: "string"
              responses:
                "201":
                  description: "Greeting submitted successfully"
                "400":
                  description: "Bad request"
        EOF
  build:
    commands:
      # Create the REST API on API Gateway
      - aws apigateway create-rest-api --name "MyAPI" --region "eu-north-1" > rest_api.json
      # Extract the API ID from the response
      - export API_ID=$(jq -r '.id' rest_api.json)
      - echo $API_ID
      # Create resources
      - aws apigateway create-resource --rest-api-id $API_ID --region "eu-north-1" --parent-id "null" --path-part resource1 > resource1.json
      # Extract resource IDs 
      - export RESOURCE1_ID=$(jq -r '.id' resource1.json)
      # Define methods
      - aws apigateway put-method --rest-api-id $API_ID --region "eu-north-1" --resource-id $RESOURCE1_ID --http-method GET --authorization-type "NONE"
      - aws apigateway put-method --rest-api-id $API_ID --region "eu-north-1" --resource-id $RESOURCE1_ID --http-method POST --authorization-type "NONE"
      # Integrate methods with backend services if needed
  post_build:
    commands:
      - echo "API Gateway setup complete."
