version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
    # Create the REST API on API Gateway
    - aws apigateway create-rest-api --name "MyAPI-2" --region "eu-north-1" --endpoint-configuration types=REGIONAL > rest_api.json
    # Extract the API ID from the response
    - export API_ID=$(jq -r '.id' rest_api.json)
    - echo $API_ID
    # Extract root resource ID
    - export ROOT_RESOURCE_ID=$(jq -r '.rootResourceId' rest_api.json)
    - echo $ROOT_RESOURCE_ID
    # Create child resources
    - aws apigateway create-resource --rest-api-id $API_ID --region "eu-north-1" --parent-id $ROOT_RESOURCE_ID --path-part "hello" > resource1.json
    # Extract resource IDs 
    - export RESOURCE1_ID=$(jq -r '.id' resource1.json)
    - echo $RESOURCE1_ID
    # Define methods
    - aws apigateway put-method --rest-api-id $API_ID --resource-id $RESOURCE1_ID --http-method GET --authorization-type "NONE"
    - aws apigateway put-method --rest-api-id $API_ID --resource-id $RESOURCE1_ID --http-method POST --authorization-type "NONE"
    # Define Integration Methods
    - aws apigateway put-integration --rest-api-id $API_ID --resource-id $RESOURCE1_ID --http-method GET --type HTTP --integration-http-method GET --uri https://jsonplaceholder.typicode.com/todos/1
    - aws apigateway put-integration --rest-api-id $API_ID --resource-id $RESOURCE1_ID --http-method POST --type HTTP --integration-http-method POST --uri https://jsonplaceholder.typicode.com/todos/1
    # Create New API Key
    #- aws apigateway create-api-key  --name MyAPIKey --description "My API Key for Testing" --enabled true
    # Define deployment and stage
    - aws apigateway create-deployment --rest-api-id $API_ID --stage-name dev --description "Initial deployment" > deploy.json
    - export deploy_ID=$(jq -r '.id' deploy.json)
    - echo $deploy_ID
    - aws apigateway create-stage --rest-api-id $API_ID --stage-name qa --deployment-id $deploy_ID --description "Testing stage"
  post_build:
    commands:
      - echo "API Gateway setup complete."
